PROJECT_NAME="xenon-shard-259622"
TERRAFORM_SERVICE_ACCOUNT_NAME="terraform-runner"
TERRAFORM_SERVICE_ACCOUNT_DISPLAY_NAME="Terraform Runner"
GCLOUD_REGION="us-central1"
GCLOUD_ZONE="us-central1-c"
GCLOUD_CREDENTIALS_FOLDER_PATH="$(pwd)/.gcloud-credentials"
GOOGLE_APPLICATION_CREDENTIALS="$GCLOUD_CREDENTIALS_FOLDER_PATH/terraform-runner.json"

export GOOGLE_CLOUD_PROJECT=$PROJECT_NAME
export GCLOUD_REGION=$GCLOUD_REGION
export GCLOUD_ZONE=$GCLOUD_ZONE
export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS