PROJECT_NAME=$(gcloud config get-value project)
TERRAFORM_SERVICE_ACCOUNT_NAME="terraform-runner"
TERRAFORM_SERVICE_ACCOUNT_DISPLAY_NAME="Terraform Runner"
GCLOUD_CREDENTIALS_FOLDER_PATH="$(pwd)/.gcloud-credentials"
GOOGLE_APPLICATION_CREDENTIALS="$GCLOUD_CREDENTIALS_FOLDER_PATH/terraform-runner.json"

export GOOGLE_CLOUD_PROJECT=$PROJECT_NAME
export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS